Update 0-run

diff --git a/0x00-python-hello_world/0-run b/0x00-python-hello_world/0-run
--- a/0x00-python-hello_world/0-run
+++ b/0x00-python-hello_world/0-run
@@ -1,2 +1,13 @@
 #!/bin/bash
-python3 $PYFILE
+
+# Get the Python script file name from the environment variable
+PYFILE="$PYFILE"
+
+# Check if the PYFILE variable is set
+if [ -z "$PYFILE" ]; then
+    echo "Error: PYFILE environment variable is not set."
+    exit 1
+fi
+
+# Run the Python script
+python3 "$PYFILE"
